spring:
  application:
    name: api-gateway

server:
  port: 8082
  


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-Url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost